import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/provider";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const urbanist = Urbanist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TravelVista",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${urbanist.className} antialiased`}>

        

        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>

      </body>
    </html>
  );
}